name: Auto-Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    - name: Run Recon
      run: python recon/recon.py
    - name: Run Vulnerability Scan
      run: python scan/vuln_scan.py
    - name: Run Exploit
      run: python exploit/exploit.py
